name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.12.0"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: gleam deps download
        working-directory: redraw
      - run: gleam test
        working-directory: redraw
      - run: gleam format --check src test
        working-directory: redraw
      - run: gleam deps download
        working-directory: redraw_dom
      - run: gleam test
        working-directory: redraw_dom
      - run: gleam format --check src test
        working-directory: redraw_dom
